# Generated by Django 6.0.4 on 2026-05-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0014_alter_decyzja_chat_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decyzja',
            name='tresc',
            field=models.TextField(help_text='Enter the exact wording of the law as it is to be applied.', max_length=2000, null=True, verbose_name='Law text'),
        ),
    ]
