# Generated by Django 6.0.4 on 2026-05-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0015_alter_decyzja_tresc'),
    ]

    operations = [
        migrations.AddField(
            model_name='decyzja',
            name='wymaga_kary',
            field=models.BooleanField(default=False, help_text='Check this box if the rule execution depends on human action and requires a penalty for non-compliance.', verbose_name='Add penalty if execution is not automatic'),
        ),
        migrations.AlterField(
            model_name='decyzja',
            name='kara',
            field=models.TextField(blank=True, help_text='What is the penalty for non-compliance with this rule. This can be, for example: "Banishment for 3 months", "Banishment forever", etc.', max_length=500, null=True, verbose_name='Penalty for non-compliance'),
        ),
    ]
