# Generated by Django 6.0.4 on 2026-06-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0017_alter_decyzja_tresc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decyzja',
            name='wymaga_kary',
        ),
    ]
