# Generated by Django 6.0.4 on 2026-06-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0018_remove_wymaga_kary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decyzja',
            name='kara',
            field=models.TextField(blank=True, help_text='Fill in only if the rule execution depends on human action and is not automatic. What is the penalty for non-compliance? This can be, for example: "Banishment for 3 months", "Banishment forever", etc.', max_length=500, null=True, verbose_name='Penalty for non-compliance (optional)'),
        ),
    ]
