# Generated by Django 6.0.4 on 2026-06-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0019_alter_decyzja_kara'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
