# Generated by Django 6.0.4 on 2026-06-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0020_argument_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='content',
            field=models.TextField(help_text='Enter your argument. You can include links.', max_length=2000, verbose_name='Argument Content'),
        ),
    ]
