# Generated by Django 6.0.3 on 2026-04-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link to event details, registration, or location', verbose_name='Link to the meeting'),
        ),
    ]
