# Generated by Django 6.0.3 on 2026-04-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0024_transaction_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True, verbose_name='Outgoing amount'),
        ),
    ]
