# Generated by Django 6.0.4 on 2026-04-27 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0025_alter_transaction_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, verbose_name='Decimal places')),
                ('is_currency', models.BooleanField(default=True, verbose_name='Is currency')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookkeeping.asset', verbose_name='Asset'),
        ),
    ]
