# Generated by Django 6.0.4 on 2026-04-27 16:23

import django.db.models.deletion
from django.db import connection, migrations, models


def create_asset_table(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='bookkeeping_asset'")
        if cursor.fetchone():
            cursor.execute("PRAGMA table_info(bookkeeping_asset)")
            columns = [row[1] for row in cursor.fetchall()]
            if 'validity' in columns or 'notes' in columns:
                cursor.execute("SELECT id, name, symbol FROM bookkeeping_asset")
                old_assets = cursor.fetchall()
                cursor.execute("DROP TABLE bookkeeping_asset")
                cursor.execute("""
                    CREATE TABLE bookkeeping_asset (
                        id INTEGER PRIMARY KEY,
                        code VARCHAR(10) UNIQUE NOT NULL,
                        name VARCHAR(100) NOT NULL,
                        symbol VARCHAR(10),
                        decimal_places SMALLINT NOT NULL DEFAULT 2,
                        is_currency BOOL NOT NULL DEFAULT 1
                    )
                """)
                asset_mapping = {
                    'Złotówki': ('PLN', 'Polski złoty', 'zł', 2, 1),
                    'Członkostwo': ('CZL', 'Członkostwo', 'czł', 0, 0),
                }
                for old_id, old_name, old_symbol in old_assets:
                    if old_name in asset_mapping:
                        code, name, symbol, decimal_places, is_currency = asset_mapping[old_name]
                        cursor.execute(
                            "INSERT INTO bookkeeping_asset (id, code, name, symbol, decimal_places, is_currency) VALUES (?, ?, ?, ?, ?, ?)",
                            (old_id, code, name, symbol, decimal_places, is_currency)
                        )
        else:
            cursor.execute("""
                CREATE TABLE bookkeeping_asset (
                    id INTEGER PRIMARY KEY,
                    code VARCHAR(10) UNIQUE NOT NULL,
                    name VARCHAR(100) NOT NULL,
                    symbol VARCHAR(10),
                    decimal_places SMALLINT NOT NULL DEFAULT 2,
                    is_currency BOOL NOT NULL DEFAULT 1
                )
            """)

        cursor.execute("PRAGMA table_info(bookkeeping_transaction)")
        tx_columns = [row[1] for row in cursor.fetchall()]
        if 'asset_id' not in tx_columns:
            cursor.execute("ALTER TABLE bookkeeping_transaction ADD COLUMN asset_id INTEGER")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0025_alter_transaction_amount'),
    ]

    operations = [
        migrations.RunPython(create_asset_table, noop),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True, verbose_name='Amount'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Asset',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                        ('name', models.CharField(max_length=100, verbose_name='Name')),
                        ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                        ('decimal_places', models.PositiveSmallIntegerField(default=2, verbose_name='Decimal places')),
                        ('is_currency', models.BooleanField(default=True, verbose_name='Is currency')),
                    ],
                    options={'ordering': ['code']},
                ),
                migrations.AddField(
                    model_name='transaction',
                    name='asset',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookkeeping.asset', verbose_name='Asset'),
                ),
            ],
            database_operations=[],
        ),
    ]
