# Generated by Django 6.0.4 on 2026-05-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0027_data_default_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Main asset shown on the dashboard. Only one asset can be marked as default at a time — selecting a new one automatically unmarks the previous.', verbose_name='Default asset'),
        ),
    ]
