# Generated by Django 6.0.4 on 2026-05-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0028_asset_is_default'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_asset'),
        ),
    ]
