# Generated by Django 6.0.4 on 2026-04-24 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_room_tracked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='votes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
