# Generated by Django 6.0.4

from django.db import migrations


def transfer_votes_to_jsonfield(apps):
    """
    Transfer data from MessageVote table to votes JSONField on Message.
    Builds a mapping of {user_id: 1/-1} for each message.
    """
    Message = apps.get_model('chat', 'Message')
    MessageVote = apps.get_model('chat', 'MessageVote')

    # Get all messages that have votes
    messages_with_votes = Message.objects.filter(votes__isnull=False)

    for message in messages_with_votes:
        # Get all votes for this message
        votes_qs = MessageVote.objects.filter(message=message)
        votes_dict = {}
        for vote in votes_qs:
            vote_value = 1 if vote.vote == 'upvote' else -1
            votes_dict[str(vote.user_id)] = vote_value

        # Update the message's votes JSONField
        message.votes = votes_dict
        message.save(update_fields=['votes'])


def reverse_transfer(apps):
    """
    Reverse migration: clear the votes JSONField.
    """
    Message = apps.get_model('chat', 'Message')
    Message.objects.update(votes={})


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_add_votes_jsonfield_to_message'),
    ]

    operations = [
        migrations.RunPython(transfer_votes_to_jsonfield, reverse_transfer),
    ]