# Generated by Django 6.0.4 on 2026-04-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_transfer_votes_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagevote',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='messagevote',
            name='chat_messagevote_msg_vote_idx',
        ),
        migrations.DeleteModel(
            name='MessageVote',
        ),
    ]
