# Generated by Django 6.0.4 on 2026-04-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_populate_reactions_from_old_tables'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='messagereaction',
            name='chat_msgreact_idx',
        ),
        migrations.AlterUniqueTogether(
            name='messagevote',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='messagevote',
            name='chat_messagevote_msg_vote_idx',
        ),
        migrations.RemoveField(
            model_name='messagevote',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagevote',
            name='user',
        ),
        migrations.DeleteModel(
            name='MessageReaction',
        ),
        migrations.DeleteModel(
            name='MessageVote',
        ),
    ]
