# Generated by Django 6.0.4 on 2026-04-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_delete_vote_and_reaction_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reactions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
