# Generated by Django 6.0.4 on 2026-05-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_onboardingprogress_step1_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='content_type',
            field=models.CharField(choices=[('post', 'Post'), ('task', 'Task'), ('event', 'Event'), ('message', 'Message'), ('decision', 'Decision'), ('citizen', 'Citizen Activity')], max_length=20),
        ),
        migrations.AlterField(
            model_name='readstatus',
            name='content_type',
            field=models.CharField(choices=[('post', 'Post'), ('task', 'Task'), ('event', 'Event'), ('message', 'Message'), ('decision', 'Decision'), ('citizen', 'Citizen Activity')], max_length=20),
        ),
    ]
