# Generated by Django 6.0.3 on 2026-04-23 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_room_tracked_by'),
        ('tasks', '0005_task_chat_room_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='chat_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='chat.room', verbose_name='Chat room'),
        ),
    ]
