# Generated by Django 6.0.4 on 2026-04-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_chat_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('it', 'Wikikracja i IT'), ('internal', 'Sprawy Wewnętrzne LO'), ('education', 'Edukacja i Wiedza'), ('promo', 'Promocja i Zasięgi'), ('resources', 'Zasoby i Biznes'), ('intervention', 'Interwencja Obywatelska'), ('other', 'Inne')], default='other', max_length=16),
        ),
    ]
