# Generated by Django 6.0.4 on 2026-05-22 23:27

import site_settings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='brand_mark',
            field=models.ImageField(blank=True, help_text='Graphic mark (longest side 512-1024 px, max 1 MB). Non-square images are letterboxed to a square on save. Source for favicon and PWA icons.', null=True, upload_to='site_branding/', validators=[site_settings.validators.validate_branding_image_size, site_settings.validators.validate_brand_mark_dimensions, site_settings.validators.validate_brand_mark_format], verbose_name='Brand mark'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brand_mark_dark',
            field=models.ImageField(blank=True, help_text='Optional variant for dark themes. Falls back to the main brand mark if empty.', null=True, upload_to='site_branding/', validators=[site_settings.validators.validate_branding_image_size, site_settings.validators.validate_brand_mark_dimensions, site_settings.validators.validate_brand_mark_format], verbose_name='Brand mark (dark themes)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='branding_text',
            field=models.CharField(blank=True, default='', help_text='Optional name displayed in the header next to the brand mark. Defaults to the site name from Django Sites if empty.', max_length=50, verbose_name='Branding text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
