# Generated by Django 6.0.4 on 2026-05-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_add_system_category_and_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
